// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCreation.Model;

#nullable disable

namespace WebApiCreation.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiCreation.Model.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("WebApiCreation.Model.Category", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CatId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            CategoryName = "E-readers"
                        },
                        new
                        {
                            CatId = 2,
                            CategoryName = "Books"
                        },
                        new
                        {
                            CatId = 3,
                            CategoryName = "Computers"
                        },
                        new
                        {
                            CatId = 4,
                            CategoryName = "laptop"
                        },
                        new
                        {
                            CatId = 5,
                            CategoryName = "Toys"
                        },
                        new
                        {
                            CatId = 6,
                            CategoryName = "Personal Care"
                        },
                        new
                        {
                            CatId = 7,
                            CategoryName = "Watches"
                        },
                        new
                        {
                            CatId = 8,
                            CategoryName = "Fashion jewellery"
                        },
                        new
                        {
                            CatId = 9,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CatId = 10,
                            CategoryName = "Kitchen"
                        },
                        new
                        {
                            CatId = 11,
                            CategoryName = "Electronic Appliances"
                        },
                        new
                        {
                            CatId = 12,
                            CategoryName = "Beauty"
                        },
                        new
                        {
                            CatId = 13,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CatId = 14,
                            CategoryName = "Fitness & Outdoors"
                        },
                        new
                        {
                            CatId = 15,
                            CategoryName = "Stationery"
                        });
                });

            modelBuilder.Entity("WebApiCreation.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CatId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CatId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebApiCreation.Model.SecurityQuestion", b =>
                {
                    b.Property<int>("SqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SqId"));

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Question");

                    b.HasKey("SqId");

                    b.ToTable("SecurityQuestions");

                    b.HasData(
                        new
                        {
                            SqId = 1,
                            Question = "What is your mother's maiden name?"
                        },
                        new
                        {
                            SqId = 2,
                            Question = "What is the name of your first pet?"
                        },
                        new
                        {
                            SqId = 3,
                            Question = "What was your first car?"
                        },
                        new
                        {
                            SqId = 4,
                            Question = "What elementary school did you attend?"
                        },
                        new
                        {
                            SqId = 5,
                            Question = "What is the name of the town where you were born?"
                        },
                        new
                        {
                            SqId = 6,
                            Question = "When you were young, what did you want to be when you grew up?"
                        },
                        new
                        {
                            SqId = 7,
                            Question = "Who was your childhood hero?"
                        },
                        new
                        {
                            SqId = 8,
                            Question = "Where was your best family vacation as a kid?"
                        });
                });

            modelBuilder.Entity("WebApiCreation.Model.UserDetails", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SqAns")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SqId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("SqId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("WebApiCreation.Model.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeId"));

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            UserTypeId = 1,
                            UserTypeName = "Admin"
                        },
                        new
                        {
                            UserTypeId = 2,
                            UserTypeName = "Customer"
                        },
                        new
                        {
                            UserTypeId = 3,
                            UserTypeName = "Vendor"
                        });
                });

            modelBuilder.Entity("WebApiCreation.Model.Cart", b =>
                {
                    b.HasOne("WebApiCreation.Model.Product", "Products")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiCreation.Model.UserDetails", "UserDetails")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("WebApiCreation.Model.Product", b =>
                {
                    b.HasOne("WebApiCreation.Model.Category", "Categories")
                        .WithMany("Products")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiCreation.Model.UserDetails", "UserDetails")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("WebApiCreation.Model.UserDetails", b =>
                {
                    b.HasOne("WebApiCreation.Model.SecurityQuestion", "SecurityQuestion")
                        .WithMany("UserDetails")
                        .HasForeignKey("SqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiCreation.Model.UserType", "UserType")
                        .WithMany("UserDetails")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityQuestion");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("WebApiCreation.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApiCreation.Model.Product", b =>
                {
                    b.Navigation("Carts");
                });

            modelBuilder.Entity("WebApiCreation.Model.SecurityQuestion", b =>
                {
                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("WebApiCreation.Model.UserDetails", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApiCreation.Model.UserType", b =>
                {
                    b.Navigation("UserDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
